apiVersion: v1
kind: Service
metadata:
  name: learning
  labels:
    app: learning
spec:
  selector:
    app: learning
  ports:
    - protocol: TCP
      port: 80
  clusterIP: 10.96.0.5
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
